### PR TITLE
Error "unsupported type; ..." with map[string]*struct

### LINKED ISSUE #42: Error "unsupported type; maybe include it the UnmarshalText interface or register it using custom type?" with map[string]*struct
**Code to reproduce:**
```golang
func TestMapToPtrStruct(t *testing.T) {
	s := struct {
		// pointer to struct
		M map[string]*struct {
			ID string
		}
	}{}

	vals := url.Values{
		"M[key].ID": []string{"M[key].ID"},
	}

	dec := formam.NewDecoder(nil)
	if err := dec.Decode(vals, &s); err != nil {
		t.Fatalf("error when decode %s", err)
	}

	if v, ok := s.M["key"]; !ok {
		t.Error("The key \"key\" in M does not exists")
	} else if v.ID != "M[key].ID" {
		t.Error("The value in key \"key\" of M is incorrect")
	}
}
```
**Expected:** no error
**Actual:** `error when decode formam: unsupported type; maybe include it the UnmarshalText interface or register it using custom type?`

### PR DESCRIPTION
**Pull request by Darigaaz**
fixed #42

### CODE REVIEW

File: formam.go [hunk 1]
```diff
@@ -295,19 +295,10 @@ func (dec *Decoder) traverse() error {
 			dec.traverseInMap(true)
 		}
 		dec.field = ""
+
+		dec.traverseIndirect()
```
Comment (Darigaaz) [inline formam.go:299]: I believe it must be nested in both cases `dec.field != ""` and `dec.index != ""`  
otherwise calls to `dec.traverse()` with empty `field` and `index` changes decoder state if `dec.curr` points to some `reflect.Pointer`

**Review by arp242 — APPROVED** [review]
